### ISSUE TITLE
Can we get imdb scores?

### ISSUE THREAD

**Issue by azypka** [mrwrob/netfweb#1]
Great idea, but can we get imdb, rotte tomatoes, and maybe metacritic user  scores? Filmweb  scores are not so reliable, most  poles just give low score to everything they see :)

**Comment by mrwrob** [comment]
Thanks! IMDB and Rotten Tomatoes ratings will be added at the beginning of October.

**Comment by mrwrob** [comment]
With a huge delay IMDb ratings arrived ;)

**Comment by picsi** [comment]
Related: #5
