### ISSUE TITLE
Film/Series confusion

### ISSUE THREAD

**Issue by theSplund** [mrwrob/netfweb#10]
Hi - only problem I have spotted so far is that the Film 'Young Offenders (2016)' has pulled back the IMDB rating of 8.2 which is associated with the (spin-off) Series 'Young Offenders (2018)' - the film is a 7.1, the series is 8.2.

**Comment by mrwrob** [comment]
The matching mechanism isn't perfect ;) However, you can fix it by yourself. Check out this video tutorial:
https://www.youtube.com/watch?v=73eLVFmL0lo&hl=en&cc_lang_pref=en&cc_load_policy=1

**Comment by theSplund** [comment]
Thanks, I shall check this out, though would one user's corrections get updated to all users?

**Comment by mrwrob** [comment]
Yes - during next release, mappings between netflix titles and websites will be added. You can see that for some titles you can't change score (e.g. Stranger Things). This is because their mappings has already been verified.
