### ISSUE TITLE
Too many score sources. How can I turn some of them off?

### ISSUE THREAD

**Issue by nicholasdtc** [mrwrob/netfweb#11]
I only care for IMDB and maybe metacritic. There are a lot of scores for every title and no option to remove some of them. I found a menu by clicking on the extension icon, it has a red X on it, but clicking it does nothing. Is it possible to edit some config file to remove the other rating sites, or do I need to fork the source?

**Comment by mrwrob** [comment]
The newest version, 0.7.0, introduce required feature. After clicking extension icon, you'll see checkboxes next to source scores. Unchecked source won't be displayed anymore. Please check this version and let me know if it works for you.

**Comment by nicholasdtc** [comment]
That was fast. Working as intended, thanks a lot!
