### ISSUE TITLE
Add Filmaffinity? 

### ISSUE THREAD

**Issue by l3utterfish** [mrwrob/netfweb#16]
Could you please add  https://www.filmaffinity.com ratings?
One of the biggest databases

**Comment by mrwrob** [comment]
Ok, I'll take a look.

**Comment by l3utterfish** [comment]
how are things going with this database?

**Comment by mrwrob** [comment]
I wrote to the filmaffinity.com, unfortunately no response... If someone would like to write a parsing function for film scores, I'd be happy to add it to the extension.
