### ISSUE TITLE
Wants access to www.lina.pl

### ISSUE THREAD

**Issue by mlnkrish** [mrwrob/netfweb#17]
The new update in firefox requires access to www.lina.pl, is this intentional?
<img width="1440" alt="Screenshot 2019-05-14 at 12 45 38 PM" src="https://user-images.githubusercontent.com/95013/57678163-417cd880-7646-11e9-9064-28979ff16ef7.png">

**Comment by mrwrob** [comment]
Hi, 
yes, this allows users to send information about corrected mappings between Netflix title and rating services (take a look: https://www.youtube.com/watch?v=73eLVFmL0lo). In fact, in the last version SSL to my domain was added. 

The code which uses the www.lina.pl you can find in background.js file: https://github.com/mrwrob/netfweb/blob/master/netfweb/background.js
