### ISSUE TITLE
Circle colouring is too subtle

### ISSUE THREAD

**Issue by JamesFerguson** [mrwrob/netfweb#21]
Creating an issue to go with the PR I wrote. 

I found the circle colouring too subtle to remember it was there. I had to look closely at a circle to figure out what colour it was. 

My PR make the circle borders brightly coloured and easy to see. I tried to match the colours already in use, but without the opacity.

**Comment by JamesFerguson** [comment]
This PR addresses this: https://github.com/mrwrob/netfweb/pull/20

**Comment by mrwrob** [comment]
Got it! PR merged!
