### ISSUE TITLE
Code on GitHub still getting updated?

### ISSUE THREAD

**Issue by rojnwa** [mrwrob/netfweb#23]
I've seen that the extension got updated on February 11, 2020 for Chrome and on Feb 8, 2020 for Firefox. This repository didn't get updated since May 15, 2019 though.

Could you please publish your changes to the extension on this repository as well?

**Comment by mrwrob** [comment]
Yep, extension has been abandoned for some time... I've just updated repo, and I'm going to spend some time to make it work again.
