### ISSUE TITLE
Trakt Tv

### ISSUE THREAD

**Issue by Jose-Nogueira** [mrwrob/netfweb#32]
Hi,
I am using Trakt TV to track the movies i have seen. So I have downloaded yours extension and I have made some changes to support this page. This way the links and the scores for the Trakt TV is all working using the api. I can share this.

Now I am trying to implemente a way to mark the watched movies on the netflix, also using the api of the Trakt TV.

**Comment by mrwrob** [comment]
@Jose-Nogueira, great news! Could you prepare Pull Request with TrackTv ratings?

**Comment by Jose-Nogueira** [comment]
@mrwrob I have created now a pull request with that changes.

**Comment by mrwrob** [comment]
Great job Jose! Thank you!

**Comment by Jose-Nogueira** [comment]
Thanks
Now, I am adding a feature to make a login on trakt TV and be possible to see the movies has already marked as seen on the netflix.
And maybe when you see a movie on netflix will automatically mark as seen on Trakt TV.
