### ISSUE TITLE
Ratings are not updated on the fly

### ISSUE THREAD

**Issue by mrwrob** [mrwrob/netfweb#36]
When displaying film card, ratings are not updated immediately after fetching info from service. You need to focus on another film, and only after you return the rankings will be displayed.

**Comment by Jose-Nogueira** [comment]
I have check on the temporary extension I have locally and works fine just take mabe 2 or 3 seconds to receive the score and update the on the film. I do not have need to change the focus. I have push of that and with others features

**Comment by mrwrob** [comment]
Yes, it seems to be fixed
