### ISSUE TITLE
Trakt.tv can NOT be disabled

### ISSUE THREAD

**Issue by reelism** [mrwrob/netfweb#38]
Trakt.tv is perpetually reactivated, between browser restarts, multiple attempts it still reappears enabled.

**Comment by elfez** [comment]
I'm guessing the line 
`<li><input id="track_tv_radio" class="nfw_checkbox" type="radio" name='default'> Trakt TV </li>`
in ìnfo.html` is the culprit as the spelling doesn't look correct.

**Comment by mrwrob** [comment]
Thanks, it is fixed in #41
