### ISSUE TITLE
Score not displayed in local format

### ISSUE THREAD

**Issue by quiettype** [mrwrob/netfweb#4]
https://github.com/mrwrob/netfweb/blob/52d12b2d746393406d3ec162727c266fde9e280d/netfweb/content.js#L59

Score does not render in local number format. (e.g. in Austrlalia score should be 9.1 instead of 9,1) 
To display in local format use score.toLocaleString(), as noted by Alex RoseModified in webstore comment on Mar 3, 2018. Suggested change:
`            filmBox.find(".nfw_score").html(getInfo(data[readStore]).score.toLocaleString());
`
btw - Many thanks for this awesome plugin.

**Comment by mrwrob** [comment]
Fixed! Thank you very much for pointing out the problem and solution :)
