### ISSUE TITLE
all movies have either (?) or 8,6, which is not correct when I compare it with filmweb or IMDb

### ISSUE THREAD

**Issue by kryfie** [mrwrob/netfweb#8]
Here's an example with all movies rated 8,6:

![image](https://user-images.githubusercontent.com/8158476/40885003-d5c1dffa-671e-11e8-8db7-c14883f3e364.png)

Taking first example:

Filmweb: 8,6; IMDB: 7,5

![image](https://user-images.githubusercontent.com/8158476/40885031-5507f7fe-671f-11e8-8a46-bd4ab97d84cb.png)

In real:

Filmweb 6,3
![image](https://user-images.githubusercontent.com/8158476/40885038-6e5b92ba-671f-11e8-890c-46e0d0c98ac6.png)

IMDb 6,3:

![image](https://user-images.githubusercontent.com/8158476/40885039-78db714c-671f-11e8-9111-bdccecdb6991.png)

**Comment by mrwrob** [comment]
Could you provide more details:
- what browser are you using,
- what OS,
- is this after first installation of the extension?

**Comment by kryfie** [comment]
Sure!

- chrome
- iOS on MacBook Air
- yes, this is first installation of this extension on this machine

**Comment by ItsNickBarry** [comment]
When no rating is found for a title, the Filmweb link appears to default to that of [The Green Mile](http://www.filmweb.pl/Zielona.Mila), which has an 8.6 rating.

For example, [Test Patterns](https://www.netflix.com/us-es/title/80018499) is not rated on any site outside of Netflix, but behaves in this way.

@kryfie Does the Filmweb rating for "Agent i pół" on the Netflix interface link to the correct Filmweb page, or did you search for it directly on Filmweb?

**Comment by kryfie** [comment]
I've search for it directly on Filmweb

**Comment by mrwrob** [comment]
Fixed in 0.6.9
