### ISSUE TITLE
Opera mode doesn't work?

### ISSUE THREAD

**Issue by WojtekPtak** [mrwrob/netfweb#9]
The extension works great under Firefox. Recently I started using Opera. It's possible to use chrome extensions in this browser. Unfortunately all moves are rated with "?".
The newest OSX, Opera and plugin (from Chrome store). 
OK - Chrome the same issue. I can check move and then I can see rates but not from Filmweb...
Reloading database doesn't help

**Comment by mrwrob** [comment]
Could check newest version (0.6.10). I think, it wasn't a problem with Opera. There was a change on the Netflix site and extension couldn't find title. With new installation (Opera) extension could find any titles and therefore any ratings.

**Comment by mrwrob** [comment]
Have you found time to check if the latest version works in Opera?

**Comment by WojtekPtak** [comment]
I've check it with Vivaldi too.
So - it's "lazy" loaded - many movies has scores, but for some I have to wait for a while or show details of the movie and then grade will appear.
But generally - maybe a bit slow but fixed for me now :)
